apiVersion: v1
kind: Namespace
metadata:
  name: scenario-4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: scenario-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-correct
  template:
    metadata:
      labels:
        app: app-correct
    spec:
      containers:
        - name: nginx
          image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: wrong-service
  namespace: scenario-4
spec:
  selector:
    app: app-wrong
  ports:
    - port: 80
      targetPort: 80
