apiVersion: v1
kind: Namespace
metadata:
  name: scenario-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-image
  namespace: scenario-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-image
  template:
    metadata:
      labels:
        app: bad-image
    spec:
      containers:
        - name: nginx
          image: nginx:tag-inexistente
