apiVersion: v1
kind: Namespace
metadata:
  name: scenario-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-limits
  namespace: scenario-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-limits
  template:
    metadata:
      labels:
        app: no-limits
    spec:
      containers:
        - name: nginx
          image: nginx:latest
