apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: missing-config
  template:
    metadata:
      labels:
        app: missing-config
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          envFrom:
            - configMapRef:
                name: config-inexistente
